#share file windows use //dnmp
version: "3"
services:
  php:
    build: ./build/php
    ports:
      - "9000:9000"
    volumes:
      #workdir
      - ${SERVICE_DIR}dnmp/conf/php.ini:/usr/local/etc/php/php.ini
      - ${SERVICE_DIR}dnmp/log/php:/var/log/php
      - ${WORK_DIR}sites:/sites
    # restart: always
  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SERVICE_DIR}dnmp/log/nginx/:/var/log/nginx
      - ${SERVICE_DIR}dnmp/conf/nginx/:/etc/nginx
      - ${WORK_DIR}sites/:/sites
    # links:
    #   - php
    # restart: always
  mysql:
    build: ./build/mysql
    ports:
      - "3306:3306"
    volumes:
      - ${SERVICE_DIR}dnmp/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ${SERVICE_DIR}dnmp/conf/mysql:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   # volumes:
  #   #   - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
  #   restart: always
  #   # entrypoint: ["redis-server", "/etc/redis.conf"]
  #   networks:
  #     - default
  # phpredisadmin:
  #   image: erikdubbelboer/phpredisadmin:latest
  #   ports:
  #     - "8082:80"
  #   networks:
  #     - default
  #   environment:
  #     - REDIS_1_HOST=redis
  #     - REDIS_1_PORT=6379