#share file windows use //dnmp
version: "3"
services:
  php:
    build: ./build/php
    ports:
      - "9000:9000"
    volumes:
      - //dnmp/conf/php.ini:/usr/local/etc/php/php.ini
      - //dnmp/log/php:/var/log/php
      #workdir
      - //sites/:/sites
      # - //e_d/:/webdir
    # restart: always
  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #windows
      # - //dnmp/log/nginx/:/var/log/nginx
      # - //dnmp/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - //dnmp/conf/nginx/:/etc/nginx
      # - ./conf/nginx:/etc/nginx
      - //sites/:/sites
      #workdir
      # - //e_d/:/webdir
    # restart: always
  mysql:
    build: ./build/mysql
    ports:
      - "3306:3306"
    # volumes:
      # - //dnmp/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      # - //dnmp/conf/mysql:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  redis:
    image: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    # entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8082:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379