version: "3"
services:
  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
    volumes:
      # - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./log/nginx:/var/log/nginx/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf/